export_languages: ["de_DE"]
append_commit_message: false
commit_message: 'New translations (%language%)'
files:
  - source: /lupobot-core/src/main/resources/locales/en_US.properties
    translation: /lupobot-core/src/main/resources/locales/%locale_with_underscore%.properties
  - source: /lupobot-plugins/lupobot-plugin-help/src/main/resources/locales/en_US.properties
    translation: /lupobot-plugins/lupobot-plugin-help/src/main/resources/locales/%locale_with_underscore%.properties
  - source: /lupobot-plugins/lupobot-plugin-music/src/main/resources/locales/en_US.properties
    translation: /lupobot-plugins/lupobot-plugin-music/src/main/resources/locales/%locale_with_underscore%.properties
  - source: /lupobot-plugins/lupobot-plugin-fun/src/main/resources/locales/en_US.properties
    translation: /lupobot-plugins/lupobot-plugin-fun/src/main/resources/locales/%locale_with_underscore%.properties